### ISSUE TITLE
Error while using "roslaunch laser_line_extraction example.launch"

### ISSUE THREAD

**Issue by spkadam** [kam3k/laser_line_extraction#13]
ERROR: cannot launch node of type [laser_line_extraction/line_extraction_node]: can't locate node [line_extraction_node] in package [laser_line_extraction]

**Comment by kam3k** [comment]
You need to make sure you've properly built and sourced the package. That is, after building it, running
`source devel/setup.bash` in the workspace in which it was built. See the ROS documentation for more details.
