### ISSUE TITLE
Error with rostopic echo /line_segments

### ISSUE THREAD

**Issue by mc13756** [kam3k/laser_line_extraction#15]
Hello!
I managed to run the package and visualize the lines from /marker topic through rviz. But when I am trying to access the topic /line_segments to get the list of lines I get the following error:

`ERROR: Cannot load message class for [laser_line_extraction/LineSegmentList]. Are your messages built?`

The topic appears in the list of active topics with rostopic lists, but rqt_graph does not include it. When I try to see the published messages with rostopic echo I get the error above. I tried to clean the workspace with catkin_make clean and rebuild it with catkin_make, then source again the environment but still, I get the same error. I think I am missing something here. Can you please provide any hint? 

Thanks in advance!

**Comment by mc13756** [comment]
Update: I managed to get the content of the topic with rostopic echo. I was not sourcing the environment in my current terminal (not proud for that). But rqt_graph still does not show the topic /line_segments. Any hint for that???

**Comment by kam3k** [comment]
> Update: I managed to get the content of the topic with rostopic echo. I was not sourcing the environment in my current terminal (not proud for that). But rqt_graph still does not show the topic /line_segments. Any hint for that???

Note that rqt_graph only shows topics that are being subscribed to? Is something subscribed to /line_segments? Note that rviz subscribes to /line_markers, not /line_segments.

**Comment by mc13756** [comment]
> > Update: I managed to get the content of the topic with rostopic echo. I was not sourcing the environment in my current terminal (not proud for that). But rqt_graph still does not show the topic /line_segments. Any hint for that???
> 
> Note that rqt_graph only shows topics that are being subscribed to? Is something subscribed to /line_segments? Note that rviz subscribes to /line_markers, not /line_segments.

I wasn't aware that rqt_graph shows only subscribed topics. I don't have any subscriber there yet, so it makes sense. My bad. Thanks a lot!
