### ISSUE TITLE
How to show lines on Rviz

### ISSUE THREAD

**Issue by mrc0x00** [kam3k/laser_line_extraction#18]
Hello,

Thank you for sharing the example. I am newbie on ROS. I want to try this algorithm on my project. When i launch "example.launch" there is no error but want to  see lines on Rviz. I will be glad how to implement it. I searched files but nothing found about Rviz package.

**My system:**
Hardware: Nvdia Jetson Nano 
OS: Ubuntu 18.4
ROS: Melodic version
Lidar: Slamtec Rplidar S1

**Comment by kam3k** [comment]
Sorry it will be very difficult to help you without providing a lot more information. I suggest first using `rostopic echo` to make sure the topics are publishing (e.g., `/line_markers` and `/line_segments`) and that you've added `/line_markers` in rviz. You also need to make sure the `scan_topic` parameter is properly set to the topic on which your `LaserScan` messages are being published.

**Comment by mrc0x00** [comment]
When I run rostopic echo /line_markers  command, can see data and changes of points on terminal. But when i try to add markers on Rviz, shows "frame[map]  does not exist" error

**Comment by futureaccomplish** [comment]
It is really hard to estimate what you wanna express.

**Comment by bbrunossf** [comment]
Hello, maybe I can help.
The lines are represented by its markers on Rviz. The error message you mentioned maybe can be solved editing the launch file, using an existing frame in your data.
In my case, I am using map frame too. Remember to change, in Rviz, the topic of markers (line_markers), and the fixed frame (/map). If this does not solve, maybe your data does not really have the map frame. It starts when you use a map server, like hector or geomapping. 
Beside roslaunch laser_line_extraction example.launch, you should also run roslaunch hector or any other launch file that contains a map server to start.
