### ISSUE TITLE
Need some debug guide.

### ISSUE THREAD

**Issue by eleboss** [kam3k/laser_line_extraction#2]
Hi!

I am a Msc student in China, and trying to use a UAV, assembled with a 2D-lidar, to flying in a tunnel. Lidar is using to detect the surface of the tunnel ,which can be treated as a line in 2D-lidar data.
By searching, I found your code in the github and it seems works very well. So I download and catkin_make it.
But what confuse me is, I see no segments output data from the /line_segments. I play around the parameters but nothing change, then I trying to use printf to print the data and fail again. I am new to C++ ROS coding， so can you give some advices on how to deal with this problem or usually how you debug the code?

I leave my parameter below, and my rosbag link. By the way, I am using the /scan_filtered topic.

Best,
Lin

<param name="~frequency" value="30.0" />
<param name="~frame_id" value="rplidar_link" />
<param name="~scan_topic" value="/scan_filtered" />
<param name="~publish_markers" value="true" />
<param name="~bearing_std_dev" value="1e-5" />
<param name="~range_std_dev" value="0.012" />
<param name="~least_sq_angle_thresh" value="0.0001" />
<param name="~least_sq_radius_thresh" value="0.0001" />
<param name="~max_line_gap" value="0.5" />
<param name="~min_line_length" value="0.7" />
<param name="~min_range" value="0.5" />
<param name="~min_split_dist" value="0.04" />
<param name="~outlier_dist" value="0.06" />
<param name="~min_line_points" value="10" />

bag file:
https://github.com/eleboss/UAV/blob/master/2018-01-22-15-28-43.bag

tunnel:
https://github.com/eleboss/UAV/blob/master/Screenshot%20from%202018-01-22%2015-10-25.png

**Comment by kam3k** [comment]
I'm just letting you know that I believe the problem is because your laser scans have

```
angle_min: 3.92499995232
angle_max: -0.785000026226
angle_increment: -0.00873840413988
```
That is, you have `angle_min > angle_max` and a negative `angle_increment`. I didn't anticipate this when writing the package, but I'll look into fixing it.

**Comment by kam3k** [comment]
I've fixed the issue and was successfully segmenting lines with your data using this configuration file:

```
<launch>
  <node name="line_extractor" pkg="laser_line_extraction" type="line_extraction_node" output="screen">
    <param name="~frequency" value="30.0" />
    <param name="~frame_id" value="rplidar_link" />
    <param name="~scan_topic" value="/scan_filtered" />
    <param name="~publish_markers" value="true" />
    <param name="~bearing_std_dev" value="1e-5" />
    <param name="~range_std_dev" value="0.012" />
    <param name="~least_sq_angle_thresh" value="0.0001" />
    <param name="~least_sq_radius_thresh" value="0.0001" />
    <param name="~max_line_gap" value="0.5" />
    <param name="~min_line_length" value="0.7" />
    <param name="~min_range" value="0.5" />
    <param name="~min_split_dist" value="0.04" />
    <param name="~outlier_dist" value="0.06" />
    <param name="~min_line_points" value="10" />
  </node>
</launch>
```

**Comment by eleboss** [comment]
Thanks for your quick response!

I didn't anticipate the negative problem too, thank you for finding and solving that problem so fast and well!
