### ISSUE TITLE
Does this works for 3D lidar case 

### ISSUE THREAD

**Issue by ajay1606** [kam3k/laser_line_extraction#22]
Thanks for sharing the useful repository, I just wonder will work for 3D lines in case of 3D lidar?

Appreciate any response.

**Comment by kam3k** [comment]
No, it works only with 2D lidar (it takes `LaserScan` messages as its input).

**Comment by Timple** [comment]
You might be able to get it to work using an intermediate step to convert the pointcloud to a laserscan:
http://wiki.ros.org/pointcloud_to_laserscan
