### ISSUE TITLE
distance between robot and line

### ISSUE THREAD

**Issue by johnbryant1** [kam3k/laser_line_extraction#7]
Hi, 
I want to use your package to create a wall following algorithm where instead of checking directly the distance to the wall through the laserscanner points, I want to just compute the distance to the line. I see that the output of the line_segment topic is the polar coordinates. which angle of the robot does the r value given corresponds to ? Thanks  in advance.

**Comment by kam3k** [comment]
[See Figure 2 in this paper](http://webee.technion.ac.il/control/info/Projects/Students/Oren_Doron/MLR/%F0%F1%F4%E7%201/LineFitMerge_ICRA03.pdf).

The axes in that figure are the axes of the laser scanner. The radius returned by this package is the value of R in the figure, and the angle returned by this package is the value of α.

**Comment by dlfksj** [comment]
Hi, I have a same question but I can't open the link.
Would you mind copying the figure here?

**Comment by kam3k** [comment]
@dlfksj Updated link [here](https://authors.library.caltech.edu/96691/1/01241772.pdf).
